<?php

namespace MvaModuleTemplate\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreedRepository extends EntityRepository
{
   
}
