<h1><?php echo $this->s_title; ?></h1>

<h5>Custom view index with additional variables</h5>

<div>
<?php echo 'Cippa => '.$this->cippa; ?>
<br>
<?php echo 'Foo => '.$this->foo; ?>
<br><br>
</div>

<div><a class="btn btn-success" href="<?php echo $this->url('mva-module-template/default', array('controller' => 'index', 'action' => 'new'))?>">Add</a></div>

<?php if (count($this->as_messages)) { ?>
<div style="border: 2px solid blue">
<?php foreach ($this->as_messages as $s_msg) { ?>
<p><?php echo $s_msg?></p>
<?php } ?>
</div>
<?php } ?>

<div>
<?php foreach($this->aI_entities as $I_dog) { ?>
<div class="row">
   <div class="span1">
        <?php echo $I_dog->getName()?> 
   </div>
    <div class="span">
        <i class="icon-edit"></i><a href="<?php echo $this->url('mva-module-template/crud', array('action' => 'edit', 'id' => $I_dog->getId()))?>">edit</a>
        
        <i class="icon-remove"></i><a href="<?php echo $this->url('mva-module-template/crud', array('action' => 'delete', 'id' => $I_dog->getId()))?>">delete</a>
    </div>
    
</div>
<?php } ?>
</div>